### ISSUE TITLE
Support for assuming a role using EC2 instance profile?

### ISSUE THREAD

**Issue by bz-keitaro-kobayashi** [jenkinsci/aws-credentials-plugin#15]
It would be great if we could leave the access key ID and secret access key blank to assume a role using the EC2 instance profile credentials.

**Comment by AlexejK** [comment]
Please see #20 as this does exactly that now

**Comment by jglick** [comment]
But see #29.

**Comment by alexejk** [comment]
I believe this is due to missing instance profile with right permissions. The PR supported multiple scenarios including working with cross-account bondaries and will still rely on basic credentials when role is not provided. But AWS machines need to have roles assigned either way.

**Comment by smastrorocco** [comment]
Is this still an open issue?  If I leave access key/secret key blank, and only specify role arn then the build gets access denied to assuming the role.  The EC2 instance role/profile has permission to assume the role arn specified and works if I perform in sh/cli command

**Comment by alexejk** [comment]
Is that Instance role assigned to a master or slave? Master is the one performing fetching of credentials and passing them over to the slave.

**Comment by smastrorocco** [comment]
@alexejk That worked great, thanks for clarifying.  As a side note, it would be nice to see the documentation bring some clarity around this.  Maybe I just missed it in there?  I think this is sort of a best practice in AWS vs keys so I believe more people would likely move to this if it was more well documented.

Thanks again!

**Comment by alexejk** [comment]
I agree that the best-practice is not to use "static" keys. I'm not sure where it's best to put the clarified documentation for this as it's kind of part of the Jenkins design that credentials are fetched by master (from store or whereever, depending on the plugins in use) and then pushed to the slave

**Comment by ahmaddev313** [comment]
Here is the scenario we have.  Our Jenkins master is on prem.  Can Jenkins master (onprem) have the ability to assume an AWS Role instead of using AWS Access Keys.  The goal is to get rid of AWS Access Keys.  Does something like this exists?  If so can you explain how? Links?  Would greatly appreciate it.

**Comment by alexejk** [comment]
If you are on-prem you still need to authenticate towards AWS first to get the ability to assume roles. So you will still need access/secret key as instance profiles are only for machines already on AWS.

**Comment by ahmaddev313** [comment]
> If you are on-prem you still need to authenticate towards AWS first to get the ability to assume roles. So you will still need access/secret key as instance profiles are only for machines already on AWS.

Thank you Alex.

**Comment by kivagant-ba** [comment]
That's just amazing. :D Thankfully to @alexejk (https://github.com/jenkinsci/aws-credentials-plugin/issues/29#issuecomment-430164267) I found how to do that. So to use an instance role that was already assigned to Jenkins' master and executors, I need to create an **empty secret** (no secrets, no roles, nothing, just Id and Description) with type "AWS Credentials" and just use it:

```
pipeline {
  agent { node { label 'worker' } }
  environment {
      AWS = credentials('aws-instance-role') // this is it and it is empty inside
  }
  stages {
    stage('test') {
      steps {
        script {
            sh 'dd if=/dev/zero of=file.txt count=1024 bs=1024'
            sh 'aws s3 cp --sse AES256 file.txt s3://my-bucket/'
        }
      }
    }
  }
}
```

**Comment by oshmyrko** [comment]
@kivagant-ba, your example will work even if you don't specify `AWS`. As you said, Jenkins' master and executors have assigned role, so AWS CLI will use credentials from IAM profile directly.
Please correct me if I'm wrong.

I was trying to use empty AWS credentials (Jenkins with IAM profile) with Amazon ECR plugin, but it does not work, failed with:
```
com.amazonaws.services.ecr.model.AmazonECRException: The security token included in the request is invalid. (Service: AmazonECR; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: ***)
```

**Comment by alexejk** [comment]
Jenkins IAM with profile only works just fine as long as host does see the env variables. binding credentials should do the trick. All our servers are running only that setup. However you need to make sure that profile is allowed to be assumed (this happens on master, not slave) and credentials are passed over to slave IIRC.

In our pipelines we generally have `withCredentials` block and wrap all operations in that block. And it works fine.
Plugin does set security token (3rd env variable), as well as access/secret tokens.

**Comment by oshmyrko** [comment]
Thank you for the explanation @alexejk. 

I was able to make it work only after adding `sts:AssumeRole` permissions to policies in IAM role (which is used by IAM instance profile attached to my Jenkins master) and adding ARN of this role to Jenkins aws credentials:
```
          - Sid: AssumeRole
            Effect: Allow
            Action:
            - sts:AssumeRole
            Resource: arn:aws:iam::*:role/jenkins*
```
![image](https://user-images.githubusercontent.com/10218528/73088368-c3fbae80-3edc-11ea-8158-055c76a42b58.png)

But from [your comment here](https://github.com/jenkinsci/aws-credentials-plugin/issues/29#issuecomment-430164267), it seems that it should work even without specifying IAM role in Jenkins aws credentials in case you have attached IAM instance profile to you Jenkins (in my case to Jenkins master, where I run my jobs). 

I think this needs to be clarified and documented somewhere.

**Comment by mgonzalezarkho** [comment]
@oshmyrko can you share your Jenkinsfile or your step configuration where you are using the AWS credentials?

**Comment by oshmyrko** [comment]
Hi @mgonzalezarkho, here is short example:

<details>
  <summary>Jenkinsfile example</summary>

It pulls nginx image, adds tag with ECR repository, and pushes this tag to ECR. Then pulls the image from ECR. The third stage should fail, because no credentials provided.

`aws-credentials` - Jenkins AWS credentials with specified `IAM Role To Use` only.

```
pipeline {
  agent any

  environment {
    DOCKER_REGISTRY   = '111111111111.dkr.ecr.us-east-1.amazonaws.com'
    DOCKER_REPOSITORY = 'test'
  }

  stages {  
    stage('Push Docker image') {
      steps {
        sh 'docker pull nginx:1.16-alpine'
        sh 'docker tag nginx:1.16-alpine ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:1.16-alpine'

        withDockerRegistry([credentialsId: 'ecr:us-east-1:aws-credentials', url: 'https://${DOCKER_REGISTRY}']) {
          sh "docker push ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:1.16-alpine"
        }
      }
    }

    stage('Pull Docker image with credentials') {
      steps {
        withDockerRegistry([credentialsId: 'ecr:us-east-1:aws-credentials', url: 'https://${DOCKER_REGISTRY}']) {
          sh 'docker rmi  ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:1.16-alpine'
          sh 'docker pull ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:1.16-alpine'
        }
      }
    }

    stage('Pull Docker image') {
      steps {
        sh 'docker rmi  ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:1.16-alpine'
        sh 'docker pull ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:1.16-alpine'
      }
    }
  }
}
```

</details>

**Comment by aaroncadillac** [comment]
> Thank you for the explanation @alexejk.
> 
> I was able to make it work only after adding `sts:AssumeRole` permissions to policies in IAM role (which is used by IAM instance profile attached to my Jenkins master) and adding ARN of this role to Jenkins aws credentials:
> 
> ```
>           - Sid: AssumeRole
>             Effect: Allow
>             Action:
>             - sts:AssumeRole
>             Resource: arn:aws:iam::*:role/jenkins*
> ```
> 
> ![image](https://user-images.githubusercontent.com/10218528/73088368-c3fbae80-3edc-11ea-8158-055c76a42b58.png)
> 
> But from [your comment here](https://github.com/jenkinsci/aws-credentials-plugin/issues/29#issuecomment-430164267), it seems that it should work even without specifying IAM role in Jenkins aws credentials in case you have attached IAM instance profile to you Jenkins (in my case to Jenkins master, where I run my jobs).
> 
> I think this needs to be clarified and documented somewhere.



> Thank you for the explanation @alexejk.
> 
> I was able to make it work only after adding `sts:AssumeRole` permissions to policies in IAM role (which is used by IAM instance profile attached to my Jenkins master) and adding ARN of this role to Jenkins aws credentials:
> 
> ```
>           - Sid: AssumeRole
>             Effect: Allow
>             Action:
>             - sts:AssumeRole
>             Resource: arn:aws:iam::*:role/jenkins*
> ```
> 
> ![image](https://user-images.githubusercontent.com/10218528/73088368-c3fbae80-3edc-11ea-8158-055c76a42b58.png)
> 
> But from [your comment here](https://github.com/jenkinsci/aws-credentials-plugin/issues/29#issuecomment-430164267), it seems that it should work even without specifying IAM role in Jenkins aws credentials in case you have attached IAM instance profile to you Jenkins (in my case to Jenkins master, where I run my jobs).
> 
> I think this needs to be clarified and documented somewhere.

I'm using this way to assume a role, but i get the following error

```
There was an error assuming the specified IAM role, a MFA may be required by your organization
```
The MFA isn`t required, in my terminal I can assume a role without MFA only using profiles

Can you help me?

**Comment by sp193** [comment]
Hi.

I am relatively new to this part of Jenkins.
Out of curiosity, why do we need to configure the role explicitly? When we don't want to specify an access key, that is.

Pushing a Docker image to ECR doesn't seem to work if we don't enter the role explicitly, giving the same error mentioned by @oshmyrko.

As a result of the need to assume an IAM role (that is already granted to the EC2 instance), I would need additional configuration to allow that.

**Comment by jglick** [comment]
Whatever limitation this was tracking was probably solved by #46 (or earlier), so I think this should be closed @jenkinsci/aws-credentials-plugin-developers.

**Comment by sp193** [comment]
Okay then.

It feels like the folks who commented above were content with going with role assumption, but it doesn't seem to work if you simply have the role configured into your EC2 instance profile.

I'm guessing it doesn't work for my usecase because it involves a combination of this plugin and amazon-ecr-plugin.

In the source code for amazon-ecr-plugin, AmazonECSRegistryCredential.getPassword() will call getCredentials(), which seems to get an AmazonWebServicesCredentials object (which I guess, comes from this plugin). AmazonWebServicesCredentials appears to be a CloudBees implementation of AWSCredentialsProvider, which doesn't do what DefaultAWSCredentialsProviderChain (from AWS) does. DefaultAWSCredentialsProviderChain will resolve the AWS credentials from a few providers, including EC2ContainerCredentialsProviderWrapper.

Therefore, AmazonECSRegistryCredential.getPassword() from amazon-ecr-plugin will error out when making the request with the AmazonECRClient, since the actual credentials will not be obtained from the EC2 instance's metadata via EC2ContainerCredentialsProviderWrapper.

That's my guess.
Right now, I don't think I have the appetite to work on something as complicated Jenkins, so I want to leave this as it is if the collaborators prefer to close this issue.

**Comment by jglick** [comment]
@sp193 if you are having trouble with https://plugins.jenkins.io/amazon-ecr/ I would suggest simply not using it, since it does not appear to do anything you could not do better and more simply yourself as part of your non-Jenkins-specific build scripts. (Whereas this `aws-credentials` plugin is also used by plugins such as `artifact-manager-s3` which make AWS calls from the controller and whose features cannot be satisfactorily replicated.)

**Comment by oshmyrko** [comment]
@sp193, @jglick 

I guess this miscommunication and misunderstanding happened because of a lack of documentation for this plugin.

Many users, including myself, expect that the plugin would retrieve credentials from the IAM role attached to the Jenkins master via an IAM instance profile because the [README.md](https://github.com/jenkinsci/aws-credentials-plugin/blob/master/README.md) mentions that the plugin supports IAM roles. Additionally, comments like [this one](https://github.com/jenkinsci/aws-credentials-plugin/issues/29) (see the last sentence) further add to the confusion.

However, the plugin actually supports IAM roles that can be assumed by the Jenkins master, as explained in:
- [Comment 1](https://github.com/jenkinsci/aws-credentials-plugin/issues/15#issuecomment-468196562)
   > Master is the one performing fetching of credentials and passing them over to the slave.
- [Comment 2](https://github.com/jenkinsci/aws-credentials-plugin/issues/15#issuecomment-577910948)
   > However you need to make sure that profile is allowed to be assumed (this happens on master, not slave) and credentials are passed over to slave IIRC.

This wasn't obvious to me when I first encountered this problem. My goal was to access AWS ECR repositories in the same way Docker Hub is accessed using `withDockerRegistry` or `docker.withRegistry` directives in my pipelines, which I ran on Jenkins master. The Amazon ECR plugin was needed here to convert AWS credentials into Docker login passwords, avoiding the use of aws ecr get-login-password commands.

It might seem reasonable to get AWS credentials from IAM instance profile when you have a single EC2 instance that acts as Jenkins master and agent and all jobs are executed on this instance. But when you have a Jenkins master running on a dedicated EC2 instance, and multiple Jenkins agents running on other EC2 instances, how to specify which IAM instance profile to use, the one from the master or the one from the agent instance? And what to do in case you do not have permission to change the agent's role but is able to create new roles with required permissions?

This plugin allows you to use an IAM role as regular AWS credentials in your pipelines that are executed on any Jenkins agent. However, the IAM role attached to the Jenkins master instance must have permissions to assume the IAM role specified in the credentials used in your pipeline (which is also useful for cross-account access).

**Comment by sp193** [comment]
Hi, hello!

Thank you all for your input and clarifications.

I don't any requirements to use any strategy over another, as my team will probably go with whatever I suggest.

As of last night, I went with setting the role into the AWS Credential and letting my EC2 instance assume that role.

But it is true that one-liner in my pipeline could do the Docker login for me, instead of all these mumbo jumbo. I just wasn't sure whether that is the "Jenkins" way of working. From this conversation, I am now convinced that it is a possible route to take.

Once again, thank you all.
