### ISSUE TITLE
sts:AssumeRole fails to authorise

### ISSUE THREAD

**Issue by autarchprinceps** [jenkinsci/aws-credentials-plugin#27]
I get the following error when trying to use Jenkins integrated credentials to authorise AWS operations. We use a role based concept, where one account holds all the users and lets us jump into roles into various (often customer) accounts. When I do it manually with the aws cli, there is no issue and I have definitively double and triple checked that I use the same credentials in both cases and I am running the aws cli from a job in Jenkins running on the exact same slave, with no aws configure or other credentials present.
```
FATAL: User: arn:aws:iam::xxx:user/xxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxx:role/xxx (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: xxx)
```
I tried using @AlexejK hpi which supposedly fixes some issues in AssumeRole, but to no avail.

My Jenkins is in version 2.60.1 and the plugin has version 1.21, as mentioned with or without pull request #20

**Comment by AlexejK** [comment]
A few questions there:
* Does your Jenkins *master* have correct Instance Profile role that allows it to assume role (Trust relationship, etc)
* Do you use Access/Secret keys? If *yes* - do you have correct Policy atteched to the user? My PR allows not using Access/Secret keys and allows to rely solely on Instance Profiles given trust relationships are correct.

How do your Policies look like? Feel free to mask some details out but its important to be able to distinguish between different account IDs / roles somehow - so please take that in consideration if masking away AWS ACcount ID and policies, etc.

Based on AWS Error its probably because of actually faulty setup on AWS for provided credentials/role.

**Comment by autarchprinceps** [comment]
Our Jenkins is not hosted in AWS, so no to the first point.
As for the second, as I said, using the same key and secret works, if I do so in the Jenkins job script doing sts assume-role in the aws cli, instead of using the plugin, which would be way more convenient, but should theoretically just execute the same stuff in Java instead of Python. I definitively checked for typos multiple times, copied over the key and secret again, etc.
Since it works with the aws cli with exactly the same user and role, it cannot be a mistake in the identity or policy. I would not completely rule out a AWS side error, but seems somewhat unlikely.
One question, though I doubt it has something to do with this, but is the authentication in your plugin executed on the slave, if the job is also executed there, or is it executed on the master?

**Comment by AlexejK** [comment]
Authentication is performed on master from what i can see and then credentials are sent to the slave.
If it works with AWS CLI when its running on the same machine then i doubt it's aws config issue.

**Note:** Do be aware that you have to use my PR package because otherwise there will be no AWS_SESSION_TOKEN set which will cause issues.

I've re-tested the PR again with setting Access/Secret keys and providing a full ARN for the role and it correctly assumes it prior to executing e.g aws cli commands in correct region.

Our setups are for the msot part now avoiding AWS Access/Secret key as we are running 100% on AWS, but with the PR package installed it works with both Instance profile and secret key.

**Question:** Are you getting AWS Error prior to the build starting? If yes - it's credentials plugin having an error in assume a role, if not - then something else is wrong which most likely is outside of the plugin itself.

Plugin code is simply using AWS SDK to either get basic credentials and bind them to ENV variables or if a assume role ARN is set - also tries to switch to it with STS.

**Comment by autarchprinceps** [comment]
It was a mistake on our part. Thanks for clarifying that the master executes the authentication. It seems our master is not in the same IP range we allow for AWS users.
